/**
 * Constants for color palette generation.
 * Only actively used mix values for UNIFIED_PALETTE approach.
 */

export const COLOR_MIXES = {
  // Background adjustments
  BG_DARKER: 0.05,
  BG_LIGHTER: 0.055,

  // Blue color adjustments
  BLUE_HEADING_DARKEN: 0.08,
  BLUE_INPUT_INFO_LIGHTEN: 0.22,
  BLUE_TABLE_LIGHTEN: 0.25,
  BLUE_PUNCTUATION_LIGHTEN: 0.2,

  // Cyan color adjustments
  CYAN_HEADING_LIGHTEN: 0.05,

  // Purple color adjustments
  PURPLE_BLUE_MIX: 0.3,

  // Yellow color adjustments
  YELLOW_ORANGE_MIX: 0.3,
  YELLOW_STACK_FRAME_DARKEN: 0.05,
  YELLOW_INPUT_WARNING_DARKEN: 0.12,
  YELLOW_WHITE_MIX: 0.15,

  // Red color adjustments
  RED_MUTED_BG_MIX: 0.5,
  RED_ORANGE_MIX: 0.3,
  RED_ERROR_DARKEN: 0.15,
  RED_ERROR_OUTLINE_DARKEN: 0.3,
  RED_BREAKPOINT_DARKEN: 0.2,
  RED_INPUT_ERROR_BG_MIX: 0.6,
  RED_INPUT_ERROR_BORDER_MIX: 0.4,

  // Git decorations
  BG_BLUE_GIT_MODIFIED_MIX: 0.65,
  BG_BLUE_GIT_MODIFIED_MINIMAP_MIX: 0.6,
  BG_TEAL_GIT_ADDED_MIX: 0.8,
  BG_TEAL_GIT_ADDED_MINIMAP_MIX: 0.75,
  BG_RED_GIT_DELETED_MIX: 0.7,
  BG_RED_GIT_DELETED_DARK_MIX: 0.65,
  BG_RED_GIT_DELETED_MINIMAP_MIX: 0.6,

  // Interactive elements
  BG_BLUE_HOVER_MIX: 0.08,
  BG_BLUE_SELECTED_MIX: 0.12,
  INTERACTIVE_HIGHLIGHT_LIGHTEN: 0.05,
  INTERACTIVE_TAB_INACTIVE_MODIFIED_LIGHTEN: 0.04,
  INTERACTIVE_TAB_UNFOCUSED_ACTIVE_LIGHTEN: 0.04,
  INTERACTIVE_TAB_LAST_PINNED_LIGHTEN: 0.05,

  // UI elements
  UI_DEBUG_EXCEPTION_MIX: 0.4,
  UI_DEBUG_BREAKPOINT_DISABLED_LIGHTEN: 0.2,
  UI_MENUBAR_SELECTION_DARKEN: 0.02,
  UI_DIFF_DIAGONAL_LIGHTEN: 0.08,
  UI_DIFF_UNCHANGED_LIGHTEN: 0.06,
  UI_COMMENT_DOC_MIX: 0.3,
  UI_RAW_INLINE_PUNCTUATION_MIX: 0.4,
  UI_HEADING6_MIX: 0.4,

  // Special elements
  SPECIAL_SELECTION_LIGHTEN: 0.3,
  SPECIAL_INDENT_ACTIVE_LIGHTEN: 0.15,
  SPECIAL_DISABLED_MIX: 0.4,
  SPECIAL_SCROLLBAR_LIGHTEN: 0.12,
  SPECIAL_GHOST_TEXT_MIX: 0.5,
  SPECIAL_INACTIVE_LIGHTEN: 0.1,

  // Editor elements
  ELEMENTS_INDENT_GUIDES_LIGHTEN: 0.08,
  ELEMENTS_INDENT_GUIDES_BG_LIGHTEN: 0.05,
  ELEMENTS_FOLD_BG_DARKEN: 0.04,
  ELEMENTS_CSS_PUNCTUATION_LIGHTEN: 0.2,
  ELEMENTS_INFO_MIX: 0.3,

  // Misc
  DEFAULT_LIBRARY_MIX: 0.4,
} as const
