/**
 * Константы для генерации цветовой палитры.
 * Все магические числа для lighten/darken/mix вынесены сюда для централизованного управления.
 */

export const COLOR_MIXES = {
  // Background adjustments
  BG_DARKEST: 0.08,
  BG_DARKER: 0.05,
  BG_DARK: 0.03,
  BG_EDITOR_LIGHTEN: 0.015,
  BG_LIGHT: 0.035,
  BG_LIGHTER: 0.055,
  BG_LIGHTEST: 0.075,

  // Foreground adjustments
  FG_DIM_LIGHTEN: 0.1,
  FG_MUTED_DARKEN: 0.12,
  FG_BRIGHT_LIGHTEN: 0.18,
  FG_BRIGHTER_LIGHTEN: 0.22,
  FG_BRIGHTEST_LIGHTEN: 0.28,

  // Blue color adjustments
  BLUE_PRIMARY_DARKEN: 0.35,
  BLUE_LIGHT_DARKEN: 0.15,
  BLUE_HEADING_DARKEN: 0.08,
  BLUE_INPUT_INFO_LIGHTEN: 0.22,
  BLUE_TABLE_LIGHTEN: 0.25,
  BLUE_BRACKETS_LIGHTEN: 0.15,
  BLUE_PUNCTUATION_LIGHTEN: 0.2,

  // Cyan color adjustments
  CYAN_DARK_DARKEN: 0.12,
  CYAN_MEDIUM_DARKEN: 0.18,
  CYAN_BRIGHT_LIGHTEN: 0.12,
  CYAN_REGEX_LIGHTEN: 0.25,
  CYAN_BRACKETS_LIGHTEN: 0.18,
  CYAN_HEADING_LIGHTEN: 0.05,

  // Teal color adjustments
  TEAL_DARK_DARKEN: 0.25,
  TEAL_BRACKETS_LIGHTEN: 0.1,

  // Green color adjustments
  GREEN_CYAN_MIX: 0.4,
  GREEN_BRACKETS_LIGHTEN: 0.08,

  // Purple color adjustments
  PURPLE_DARK_DARKEN: 0.15,
  PURPLE_BRIGHT_LIGHTEN: 0.08,
  PURPLE_BRACKETS_LIGHTEN: 0.12,
  PURPLE_BLUE_MIX: 0.3,

  // Yellow color adjustments
  YELLOW_LIGHT_LIGHTEN: 0.12,
  YELLOW_MUTED_DARKEN: 0.15,
  YELLOW_ORANGE_MIX: 0.3,
  YELLOW_STACK_FRAME_DARKEN: 0.05,
  YELLOW_INPUT_WARNING_DARKEN: 0.12,
  YELLOW_BRACKETS_LIGHTEN: 0.05,
  YELLOW_WHITE_MIX: 0.15,

  // Red color adjustments
  RED_DARK_DARKEN: 0.12,
  RED_MUTED_BG_MIX: 0.5,
  RED_ORANGE_MIX: 0.3,
  RED_ERROR_DARKEN: 0.15,
  RED_ERROR_OUTLINE_DARKEN: 0.3,
  RED_BREAKPOINT_DARKEN: 0.2,
  RED_INPUT_ERROR_BG_MIX: 0.6,
  RED_INPUT_ERROR_BORDER_MIX: 0.4,
  RED_PINK_MIX: 0.3,

  // Pink color adjustments
  PINK_MAIN_DARKEN: 0.18,
  PINK_PURPLE_MIX: 0.3,

  // Background mix adjustments
  BG_BLUE_HOVER_MIX: 0.08,
  BG_BLUE_SELECTED_MIX: 0.12,
  BG_BLUE_DEBUG_MIX: 0.1,
  BG_BLUE_GIT_MODIFIED_MIX: 0.65,
  BG_BLUE_GIT_MODIFIED_MINIMAP_MIX: 0.6,
  BG_TEAL_GIT_ADDED_MIX: 0.8,
  BG_TEAL_GIT_ADDED_MINIMAP_MIX: 0.75,
  BG_RED_GIT_DELETED_MIX: 0.7,
  BG_RED_GIT_DELETED_DARK_MIX: 0.65,
  BG_RED_GIT_DELETED_MINIMAP_MIX: 0.6,

  // UI adjustments
  UI_BRIGHT_WHITE_LIGHTEN: 0.35,
  UI_LINK_ACTIVE_LIGHTEN: 0.35,
  UI_CODE_LENS_DARKEN: 0.05,
  UI_DEBUG_EXCEPTION_MIX: 0.4,
  UI_DEBUG_BREAKPOINT_DISABLED_LIGHTEN: 0.2,
  UI_MENUBAR_SELECTION_DARKEN: 0.02,
  UI_DIFF_DIAGONAL_LIGHTEN: 0.08,
  UI_DIFF_UNCHANGED_LIGHTEN: 0.06,
  UI_COMMENT_DOC_MIX: 0.3,
  UI_RAW_INLINE_PUNCTUATION_MIX: 0.4,
  UI_HEADING6_MIX: 0.4,

  // Special adjustments
  SPECIAL_SELECTION_LIGHTEN: 0.3,
  SPECIAL_INDENT_ACTIVE_LIGHTEN: 0.15,
  SPECIAL_DISABLED_MIX: 0.4,
  SPECIAL_SCROLLBAR_LIGHTEN: 0.12,
  SPECIAL_GHOST_TEXT_MIX: 0.5,
  SPECIAL_INACTIVE_LIGHTEN: 0.1,

  // Interactive adjustments
  INTERACTIVE_HIGHLIGHT_LIGHTEN: 0.05,
  INTERACTIVE_TAB_INACTIVE_MODIFIED_LIGHTEN: 0.04,
  INTERACTIVE_TAB_UNFOCUSED_ACTIVE_LIGHTEN: 0.04,
  INTERACTIVE_TAB_LAST_PINNED_LIGHTEN: 0.05,

  // Elements adjustments
  ELEMENTS_INDENT_GUIDES_LIGHTEN: 0.08,
  ELEMENTS_INDENT_GUIDES_BG_LIGHTEN: 0.05,
  ELEMENTS_FOLD_BG_DARKEN: 0.04,
  ELEMENTS_CSS_PUNCTUATION_LIGHTEN: 0.2,
  ELEMENTS_INFO_MIX: 0.3,

  // Default library mix
  DEFAULT_LIBRARY_MIX: 0.4,

  // Badge color - вычисляется как смесь синего и циана
  BADGE_BLUE_CYAN_MIX: 0.55, // Оригинальный #007acc ближе к синему с небольшим цианом
} as const
