/**
 * Центральный файл экспорта типов темы
 *
 * Типы разделены на логические модули для лучшей организации кода:
 * - theme.ts - основные типы темы VS Code
 * - palette.ts - типы цветовой палитры
 */

export * from './palette.js'
export * from './theme.js'

/**
 * Тип FontStyle представляет разрешенные стили шрифта для темы VS Code
 * Может быть одним из базовых стилей, комбинацией стилей (разделенных пробелом) или пустой строкой
 */
export type FontStyle =
  | 'italic'
  | 'bold'
  | 'underline'
  | 'strikethrough'
  | 'bold italic'
  | 'italic bold'
  | 'bold underline'
  | 'underline bold'
  | 'bold strikethrough'
  | 'strikethrough bold'
  | 'italic underline'
  | 'underline italic'
  | 'italic strikethrough'
  | 'strikethrough italic'
  | 'underline strikethrough'
  | 'strikethrough underline'
  | 'bold italic underline'
  | 'bold underline italic'
  | 'italic bold underline'
  | 'italic underline bold'
  | 'underline bold italic'
  | 'underline italic bold'
  | 'bold italic strikethrough'
  | 'bold strikethrough italic'
  | 'italic bold strikethrough'
  | 'italic strikethrough bold'
  | 'strikethrough bold italic'
  | 'strikethrough italic bold'
  | 'bold underline strikethrough'
  | 'bold strikethrough underline'
  | 'underline bold strikethrough'
  | 'underline strikethrough bold'
  | 'strikethrough bold underline'
  | 'strikethrough underline bold'
  | 'italic underline strikethrough'
  | 'italic strikethrough underline'
  | 'underline italic strikethrough'
  | 'underline strikethrough italic'
  | 'strikethrough italic underline'
  | 'strikethrough underline italic'
  | 'bold italic underline strikethrough'
  | 'bold italic strikethrough underline'
  | 'bold underline italic strikethrough'
  | 'bold underline strikethrough italic'
  | 'bold strikethrough italic underline'
  | 'bold strikethrough underline italic'
  | 'italic bold underline strikethrough'
  | 'italic bold strikethrough underline'
  | 'italic underline bold strikethrough'
  | 'italic underline strikethrough bold'
  | 'italic strikethrough bold underline'
  | 'italic strikethrough underline bold'
  | 'underline bold italic strikethrough'
  | 'underline bold strikethrough italic'
  | 'underline italic bold strikethrough'
  | 'underline italic strikethrough bold'
  | 'underline strikethrough bold italic'
  | 'underline strikethrough italic bold'
  | 'strikethrough bold italic underline'
  | 'strikethrough bold underline italic'
  | 'strikethrough italic bold underline'
  | 'strikethrough italic underline bold'
  | 'strikethrough underline bold italic'
  | 'strikethrough underline italic bold'
  | ''
