import { palette } from '../palette/index'

/**
 * Editor UI элементы
 * Эти токены отвечают за оформление редактора кода в VS Code
 */
export const editorColors = {
  'editor.background': palette.background,
  'editor.findMatchBackground': palette.selection + '66',
  'editor.findMatchHighlightBackground': palette.selection + '66',
  'editor.findRangeHighlightBackground': palette.special.highlight + '33',
  'editor.focusedStackFrameHighlightBackground':
    palette.special.highlight + '20',
  'editor.foldBackground': palette.backgrounds.secondary + '4A',
  'editor.foreground': palette.foreground,
  'editor.inactiveSelectionBackground': palette.selection + '45',
  'editor.lineHighlightBackground': palette.backgrounds.elevated,
  'editor.lineHighlightBorder': palette.transparent,
  'editor.rangeHighlightBackground': palette.special.highlight + '20',
  'editor.selectionBackground': palette.selection + '60',
  'editor.selectionHighlightBackground': palette.special.highlight + '44',
  'editor.stackFrameHighlightBackground': palette.special.highlight + '20',
  'editor.wordHighlightBackground': palette.special.highlight + '44',
  'editor.wordHighlightStrongBackground': palette.special.highlight + '55',
  'editorBracketHighlight.foreground1': palette.blue,
  'editorBracketHighlight.foreground2': palette.blue,
  'editorBracketHighlight.foreground3': palette.purple,
  'editorBracketHighlight.foreground4': palette.cyan,
  'editorBracketHighlight.foreground5': palette.green,
  'editorBracketHighlight.foreground6': palette.yellow,
  'editorBracketHighlight.unexpectedBracket.foreground': palette.error,
  'editorBracketMatch.background': palette.backgrounds.secondary,
  'editorBracketMatch.border': palette.borders.subtle,
  'editorBracketPairGuide.activeBackground1': palette.blue,
  'editorBracketPairGuide.activeBackground2': palette.blue,
  'editorBracketPairGuide.activeBackground3': palette.purple,
  'editorBracketPairGuide.activeBackground4': palette.cyan,
  'editorBracketPairGuide.activeBackground5': palette.green,
  'editorBracketPairGuide.activeBackground6': palette.yellow,
  'editorCodeLens.foreground': palette.textSecondary,
  'editorCursor.background': palette.backgrounds.secondary,
  'editorCursor.foreground': palette.yellow,
  'editorError.foreground': palette.error,
  'editorHint.foreground': palette.info,
  'editorHoverWidget.background': palette.backgrounds.secondary,
  'editorHoverWidget.border': palette.borders.subtle + '40',
  'editorIndentGuide.activeBackground1': palette.borders.subtle + '40',
  'editorIndentGuide.activeBackground2': palette.borders.subtle + '40',
  'editorIndentGuide.activeBackground3': palette.borders.subtle + '40',
  'editorIndentGuide.activeBackground4': palette.borders.subtle + '40',
  'editorIndentGuide.activeBackground5': palette.borders.subtle + '40',
  'editorIndentGuide.activeBackground6': palette.borders.subtle + '40',
  'editorIndentGuide.background1': palette.borders.subtle + '20',
  'editorIndentGuide.background2': palette.borders.subtle + '20',
  'editorIndentGuide.background3': palette.borders.subtle + '20',
  'editorIndentGuide.background4': palette.borders.subtle + '20',
  'editorIndentGuide.background5': palette.borders.subtle + '20',
  'editorIndentGuide.background6': palette.borders.subtle + '20',
  'editorInfo.foreground': palette.info,
  'editorLightBulb.foreground': palette.yellow,
  'editorLightBulbAutoFix.foreground': palette.yellow,
  'editorLineNumber.activeForeground': palette.text,
  'editorLineNumber.foreground': palette.textSecondary,
  'editorLink.activeForeground': palette.text,
  'editorMarkerNavigation.background': palette.backgrounds.secondary,
  'editorOverviewRuler.border': palette.transparent,
  'editorOverviewRuler.bracketMatchForeground': palette.backgrounds.secondary,
  'editorRuler.foreground': palette.borders.subtle,
  'editorStickyScroll.background': palette.backgrounds.secondary,
  'editorStickyScroll.shadow': palette.special.shadow + '80',
  'editorStickyScrollHover.background': palette.interactive.hover,
  'editorSuggestWidget.background': palette.backgrounds.secondary,
  'editorSuggestWidget.border': palette.borders.subtle + '40',
  'editorSuggestWidget.foreground': palette.foreground,
  'editorSuggestWidget.highlightForeground': palette.borders.subtle,
  'editorSuggestWidget.selectedBackground': palette.interactive.selected,
  'editorWarning.foreground': palette.yellow,
  'editorWhitespace.foreground': palette.textSecondary,
  'editorWidget.background': palette.backgrounds.secondary,
  'editorWidget.resizeBorder': palette.special.highlight + '33',
}
