import { palette } from './palette'

export const colors = {
  'commandCenter.background': palette.background,
  'commandCenter.activeBackground': palette.backgroundPanel,
  'commandCenter.border': palette.border,
  'diffEditor.insertedTextBackground': palette.accentGreen + palette.alpha1f,
  'diffEditor.removedTextBackground': palette.accentRed + palette.alpha1f,
  'diffEditor.insertedLineBackground': palette.accentGreen + palette.alpha14,
  'diffEditor.removedLineBackground': palette.accentRed + palette.alpha14,
  'diffEditor.diagonalFill': palette.backgroundPanel,
  'merge.border': palette.border,
  'merge.currentHeaderBackground': palette.accentGreen + palette.alpha1f,
  'merge.currentContentBackground': palette.accentGreen + palette.alpha0f,
  'merge.incomingHeaderBackground': palette.accentBlue + palette.alpha1f,
  'merge.incomingContentBackground': palette.accentBlue + palette.alpha0f,
  'merge.commonHeaderBackground': palette.accentYellow + palette.alpha1a,
  'merge.commonContentBackground': palette.accentYellow + palette.alpha0d,
  foreground: palette.foreground,
  'icon.foreground': palette.foregroundInactive,
  descriptionForeground: palette.foregroundAlt,
  disabledForeground: palette.foregroundAlt,
  focusBorder: palette.alpha00,
  errorForeground: palette.accentRed,
  'selection.background': palette.selectionBlueAlpha,
  'editor.background': palette.background,
  'editor.foreground': palette.foreground,
  'editor.selectionBackground': palette.selectionBlueAlpha,
  'editor.inactiveSelectionBackground': palette.alpha1fFull,
  'editor.lineHighlightBackground': palette.alpha1fFull,
  'editorLineNumber.foreground': palette.grayDark,
  'editorLineNumber.activeForeground': palette.editorLineNumberActive,
  'editorCursor.foreground': palette.foregroundAlt,
  'editorIndentGuide.background1': palette.border,
  'editorIndentGuide.activeBackground1': palette.selectionBlueAlphaLight,
  'editorStickyScroll.background': palette.backgroundAlt,
  'editorStickyScrollHover.background': palette.alpha1fFull,
  'editor.placeholder.foreground': palette.foregroundInactive,
  'editor.foldPlaceholderForeground': palette.foregroundAlt,
  'sideBar.background': palette.backgroundSidebar,
  'sideBar.foreground': palette.foreground,
  'sideBar.border': palette.border,
  'sideBarSectionHeader.background': palette.backgroundPanel,
  'sideBarSectionHeader.foreground': palette.foreground,
  'activityBar.background': palette.backgroundAlt,
  'activityBar.foreground': palette.foregroundAlt,
  'activityBar.inactiveForeground': palette.activityBarInactive,
  'activityBar.activeBorder': palette.accentBlue,
  'activityBar.activeBackground': palette.background,
  'activityBar.activeFocusBorder': palette.selectionBlueAlphaLight,
  'activityBar.border': palette.border,
  'activityBar.dropBorder': palette.accentBlue,
  'statusBar.background': palette.backgroundAlt,
  'statusBar.foreground': palette.foregroundAlt,
  'statusBar.border': palette.border,
  'statusBarItem.remoteBackground': palette.blueStrong,
  'statusBarItem.remoteForeground': palette.white,
  'statusBarItem.remoteHoverBackground': palette.blueHover,
  'statusBarItem.remoteHoverForeground': palette.white,
  'statusBarItem.hoverBackground': palette.alpha1fFull,
  'statusBarItem.hoverForeground': palette.foreground,
  'statusBarItem.compactHoverBackground': palette.alpha1fFull,
  'statusBarItem.activeBackground': palette.accentBlue + palette.alpha33,
  'statusBarItem.focusBorder': palette.selectionBlueAlphaLight,
  'statusBar.focusBorder': palette.selectionBlueAlphaLight,
  'statusBarItem.prominentBackground': palette.blueStrong,
  'statusBarItem.prominentForeground': palette.white,
  'statusBarItem.prominentHoverBackground': palette.blueHover,
  'statusBarItem.prominentHoverForeground': palette.white,
  'tab.activeBackground': palette.background,
  'tab.activeForeground': palette.foreground,
  'tab.activeBorderTop': palette.accentBlue,
  'tab.inactiveBackground': palette.backgroundAlt,
  'tab.inactiveForeground': palette.foregroundAlt,
  'tab.hoverBackground': palette.alpha1fFull,
  'tab.hoverForeground': palette.foreground,
  'tab.border': palette.border,
  'tab.lastPinnedBorder': palette.borderAlt,
  'tab.unfocusedActiveBackground': palette.background + palette.alphaCC,
  'tab.unfocusedActiveForeground': palette.foreground + palette.alphaCC,
  'tab.unfocusedInactiveForeground': palette.foregroundAlt + palette.alpha99,
  'textBlockQuote.background': palette.backgroundPanel,
  'textBlockQuote.border': palette.accentBlue + palette.alpha59,
  'titleBar.activeBackground': palette.backgroundAlt,
  'titleBar.inactiveBackground': palette.backgroundAlt,
  'titleBar.activeForeground': palette.foreground,
  'titleBar.inactiveForeground': palette.foregroundAlt,
  'titleBar.border': palette.border,
  'editorGroupHeader.tabsBackground': palette.backgroundAlt,
  'editorGroupHeader.noTabsBackground': palette.backgroundAlt,
  'editorGroupHeader.tabsBorder': palette.border,
  'editorGroup.border': palette.border,
  'editorGroup.emptyBackground': palette.background,
  'editorGroup.focusedEmptyBorder': palette.selectionBlueAlphaLight,
  'panel.background': palette.background,
  'panel.border': palette.border,
  'panelSectionHeader.background': palette.background,
  'panelSectionHeader.foreground': palette.foreground,
  'panelTitle.activeForeground': palette.foreground,
  'panelTitle.inactiveForeground': palette.foregroundAlt,
  'panelTitle.activeBorder': palette.accentBlue,
  'panelTitle.border': palette.border,
  'panel.dropBorder': palette.selectionBlueAlphaBorder,
  'panelTitleBadge.background': palette.blueStrong,
  'panelTitleBadge.foreground': palette.white,
  'panelSection.border': palette.grayBadge,
  'panelSectionHeader.border': palette.grayBadge,
  'list.activeSelectionBackground': palette.selectionBlueAlpha,
  'list.activeSelectionForeground': palette.foreground,
  'list.inactiveSelectionBackground': palette.alpha1fFull,
  'list.inactiveSelectionForeground': palette.foreground,
  'list.hoverBackground': palette.alpha1fFull,
  'list.hoverForeground': palette.foreground,
  'list.focusBackground': palette.selectionBlueAlpha,
  'list.focusForeground': palette.foreground,
  'list.highlightForeground': palette.accentBlueAlt,
  'input.background': palette.backgroundAlt,
  'input.foreground': palette.foreground,
  'input.border': palette.border,
  'inputOption.activeBorder': palette.accentBlueAlt,
  'input.placeholderForeground': palette.foregroundInactive,
  'button.background': palette.blueStrong,
  'button.foreground': palette.white,
  'button.hoverBackground': palette.blueHover,
  'button.border': palette.accentBlueAlt,
  'button.separator': palette.blueSeparator,
  'button.secondaryBackground': palette.backgroundAlt,
  'button.secondaryForeground': palette.foreground,
  'button.secondaryHoverBackground': palette.blueSecondary,
  'badge.background': palette.blueBadge,
  'badge.foreground': palette.white,
  'activityBarBadge.background': palette.blueBadge,
  'activityBarBadge.foreground': palette.white,
  'activityWarningBadge.background': palette.yellowBadge,
  'activityWarningBadge.foreground': palette.background,
  'activityErrorBadge.background': palette.redBadge,
  'activityErrorBadge.foreground': palette.background,
  'extensionBadge.remoteBackground': palette.blueBadge,
  'extensionBadge.remoteForeground': palette.white,
  'menu.background': palette.background,
  'menu.foreground': palette.foreground,
  'menu.selectionBackground': palette.alpha00,
  'menu.selectionForeground': palette.foreground,
  'menu.selectionBorder': palette.accentBlueAlt,
  'menubar.selectionBorder': palette.accentBlueAlt,
  'menubar.selectionBackground': palette.alpha00,
  'menubar.selectionForeground': palette.foreground,
  'menu.border': palette.border,
  'menu.separatorBackground': palette.grayMenu,
  'dropdown.background': palette.background,
  'dropdown.foreground': palette.foreground,
  'dropdown.border': palette.border,
  'dropdown.listBackground': palette.background,
  'terminal.background': palette.background,
  'terminal.foreground': palette.foreground,
  'terminal.selectionBackground': palette.selectionBlueAlpha,
  'terminal.inactiveSelectionBackground': palette.alpha1fFull,
  'terminal.border': palette.border,
  'terminal.hoverHighlightBackground': palette.grayWidgetScrollbarSliderHover,
  'terminal.ansiBlack': palette.background,
  'terminal.ansiRed': palette.accentRed,
  'terminal.ansiGreen': palette.accentGreen,
  'terminal.ansiYellow': palette.accentYellow,
  'terminal.ansiBlue': palette.accentBlueAlt,
  'terminal.ansiMagenta': palette.accentPurple,
  'terminal.ansiCyan': palette.accentBlueAlt,
  'terminal.ansiWhite': palette.grayLight,
  'terminal.ansiBrightBlack': palette.gray,
  'terminal.ansiBrightRed': palette.terminalBrightRed,
  'terminal.ansiBrightGreen': palette.terminalBrightGreen,
  'terminal.ansiBrightYellow': palette.terminalBrightYellow,
  'terminal.ansiBrightBlue': palette.accentBlueAlt,
  'terminal.ansiBrightMagenta': palette.terminalBrightMagenta,
  'terminal.ansiBrightCyan': palette.accentBlueAlt,
  'terminal.ansiBrightWhite': palette.white,
  'terminalCommandDecoration.defaultBackground': palette.selectionBlueAlphaMid,
  'terminalCommandDecoration.successBackground':
    palette.accentGreen + palette.alpha33,
  'terminalCommandDecoration.errorBackground':
    palette.accentRed + palette.alpha33,
  'textLink.foreground': palette.accentBlueAlt,
  'textLink.activeForeground': palette.accentBlueAlt,
  'editorLink.activeForeground': palette.accentBlueAlt,
  'notifications.background': palette.backgroundAlt,
  'notifications.foreground': palette.foreground,
  'notifications.border': palette.border,
  'editorHoverWidget.background': palette.background,
  'editorHoverWidget.border': palette.grayWidgetBorder,
  'editorHoverWidget.highlightForeground': palette.hoverWidgetHighlight,
  'editorHoverWidget.foreground': palette.foreground,
  'editorSuggestWidget.background': palette.backgroundPanel,
  'editorSuggestWidget.border': palette.grayWidgetBorder,
  'editorSuggestWidget.highlightForeground': palette.accentBlueAlt,
  'editorSuggestWidget.selectedBackground': palette.selectionBlueAlpha,
  'editorSuggestWidget.selectedForeground': palette.foreground,
  'editorSuggestWidget.selectedIconForeground': palette.foreground,
  'quickInput.background': palette.backgroundAlt,
  'editorWidget.background': palette.backgroundAlt,
  'widget.border': palette.grayWidgetBorder,
  'widget.shadow': palette.grayShadow,
  'editorWidget.border': palette.grayWidgetBorder,
  'quickInput.foreground': palette.foreground,
  'quickInputTitle.background': palette.backgroundPanel,
  'quickInputList.focusBackground': palette.selectionBlueAlpha,
  'quickInputList.focusForeground': palette.foreground,
  'peekViewEditor.background': palette.backgroundAlt,
  'peekViewResult.background': palette.backgroundAlt,
  'peekViewTitle.background': palette.backgroundPanel,
  'peekViewEditor.matchHighlightBackground': palette.grayWidgetPeekViewMatch,
  'peekViewResult.matchHighlightBackground': palette.grayWidgetPeekViewMatch,
  'peekViewResult.selectionBackground': palette.grayWidgetPeekViewSelection,
  'list.filterMatchBackground': palette.grayWidgetFilterMatch,
  'list.filterMatchBorder': palette.grayWidgetFilterMatchBorder,
  'searchEditor.findMatchBackground': palette.grayWidgetSearchMatch,
  'searchEditor.findMatchBorder': palette.grayWidgetSearchMatchBorder,
  'editor.findMatchBackground': palette.grayWidgetFindMatch,
  'editor.findMatchBorder': palette.grayWidgetFindMatchBorder,
  'editor.findMatchHighlightBackground': palette.grayWidgetFindMatchHighlight,
  'editor.findMatchForeground': palette.foreground,
  'terminal.findMatchBackground': palette.grayWidgetTerminalFindMatch,
  'terminal.findMatchBorder': palette.grayWidgetTerminalFindMatchBorder,
  'terminal.findMatchHighlightBackground':
    palette.grayWidgetTerminalFindMatchHighlight,
  'editor.wordHighlightBackground': palette.grayWidgetWordHighlight,
  'editor.wordHighlightStrongBackground': palette.grayWidgetWordHighlightStrong,
  'editor.hoverHighlightBackground': palette.grayWidgetHoverHighlight,
  'editor.selectionHighlightBackground': palette.grayWidgetSelectionHighlight,
  'editor.selectionHighlightBorder': palette.grayWidgetSelectionHighlightBorder,
  'toolbar.hoverBackground': palette.grayWidgetToolbarHover,
  'toolbar.activeBackground': palette.grayWidgetToolbarActive,
  'toolbar.hoverOutline': palette.grayWidgetToolbarOutline,
  'debugToolBar.background': palette.grayWidgetDebugToolbar,
  'debugToolBar.border': palette.grayWidgetDebugToolbarBorder,
  'debugExceptionWidget.background': palette.grayWidgetDebugException,
  'debugExceptionWidget.border': palette.grayWidgetDebugExceptionBorder,
  'editor.stackFrameHighlightBackground': palette.grayWidgetStackFrame,
  'editor.focusedStackFrameHighlightBackground':
    palette.grayWidgetStackFrameHighlight,
  'debugIcon.breakpointForeground': palette.grayWidgetBreakpoint,
  'debugIcon.breakpointDisabledForeground':
    palette.grayWidgetBreakpointDisabled,
  'debugIcon.breakpointUnverifiedForeground':
    palette.grayWidgetBreakpointUnverified,
  'debugIcon.breakpointCurrentStackframeForeground':
    palette.grayWidgetBreakpointCurrent,
  'debugIcon.breakpointStackframeForeground': palette.grayWidgetBreakpointStack,
  'inlineChat.background': palette.grayWidgetInlineChat,
  'inlineChat.foreground': palette.grayWidgetInlineChatForeground,
  'inlineChat.border': palette.grayWidgetInlineChatBorder,
  'inlineChatInput.placeholderForeground': palette.grayWidgetInlineChatInput,
  'scrollbar.shadow': palette.grayScrollbar,
  'scrollbarSlider.background': palette.grayWidgetScrollbarSlider,
  'scrollbarSlider.hoverBackground': palette.grayWidgetScrollbarSliderHover,
  'scrollbarSlider.activeBackground': palette.grayWidgetScrollbarSliderActive,
  'editor.rangeHighlightBackground': palette.grayWidgetRangeHighlight,
  'editorOverviewRuler.findMatchForeground':
    palette.grayWidgetOverviewRulerFindMatch,
  'editorOverviewRuler.selectionHighlightForeground':
    palette.grayWidgetOverviewRulerSelectionHighlight,
  'editorOverviewRuler.rangeHighlightForeground':
    palette.grayWidgetOverviewRulerRangeHighlight,
  'editorOverviewRuler.wordHighlightForeground':
    palette.grayWidgetOverviewRulerWordHighlight,
  'editorOverviewRuler.wordHighlightStrongForeground':
    palette.grayWidgetOverviewRulerWordHighlightStrong,
  'minimap.findMatchHighlight': palette.grayWidgetMinimapFindMatch,
  'minimap.selectionHighlight': palette.grayWidgetMinimapSelectionHighlight,
  'editorGroup.dropBackground': palette.grayWidgetEditorGroupDrop,
  'list.dropBackground': palette.grayWidgetListDrop,
  'panelSection.dropBackground': palette.grayWidgetPanelSectionDrop,
  'terminal.dropBackground': palette.grayWidgetTerminalDrop,
}
