import { palette } from '../../palette'
import { alpha, lighten } from '../../utils/color'

export function generateEditorColors(): Record<string, string> {
  const {
    bg,
    fg,
    blue,
    cyan,
    yellow,
    red,
    purple,
    teal,
    ui,
    brackets,
    git,
    interactive,
    elements,
    special,
  } = palette

  return {
    'selection.background': alpha(interactive.highlight, 0.2),
    'editor.background': bg.editor,
    'editor.foreground': fg.brighter,
    'editor.foldBackground': alpha(elements.foldBackground, 0.2),
    'editorLink.activeForeground': ui.linkActive,
    'editor.selectionBackground': alpha(interactive.highlight, 0.2),
    'editor.inactiveSelectionBackground': alpha(interactive.highlight, 0.2),
    'editor.findMatchBackground': alpha(blue.light, 0.2),
    'editor.findMatchBorder': yellow.main,
    'editor.findMatchHighlightBackground': alpha(blue.light, 0.2),
    'editor.findRangeHighlightBackground': alpha(interactive.selected, 0.2),
    'editor.rangeHighlightBackground': alpha(teal.main, 0.2),
    'editor.wordHighlightBackground': alpha(purple.light, 0.2),
    'editor.wordHighlightStrongBackground': alpha(purple.bright, 0.2),
    'editor.selectionHighlightBackground': alpha(cyan.medium, 0.2),
    'editorCursor.foreground': fg.brightest,
    'editorIndentGuide.background1': elements.indentGuidesBackground,
    'editorIndentGuide.activeBackground1': special.indentActive,
    'editorLineNumber.foreground': special.indentActive,
    'editorLineNumber.activeForeground': fg.medium,
    'editor.lineHighlightBackground': bg.lighter,
    'editorWhitespace.foreground': special.indentActive,
    'editorMarkerNavigation.background': bg.main,
    'editorHoverWidget.background': bg.light,
    'editorHoverWidget.border': lighten(bg.light, 0.04),
    'editorBracketMatch.background': bg.main,
    'editorBracketMatch.border': special.indentActive,
    'editorBracketHighlight.foreground1': brackets.blue,
    'editorBracketHighlight.foreground2': brackets.cyan,
    'editorBracketHighlight.foreground3': brackets.purple,
    'editorBracketHighlight.foreground4': brackets.teal,
    'editorBracketHighlight.foreground5': brackets.green,
    'editorBracketHighlight.foreground6': yellow.muted,
    'editorBracketHighlight.unexpectedBracket.foreground': red.dark,
    'editorBracketPairGuide.activeBackground1': brackets.blue,
    'editorBracketPairGuide.activeBackground2': brackets.cyan,
    'editorBracketPairGuide.activeBackground3': brackets.purple,
    'editorBracketPairGuide.activeBackground4': brackets.teal,
    'editorBracketPairGuide.activeBackground5': brackets.green,
    'editorBracketPairGuide.activeBackground6': yellow.muted,
    'editorOverviewRuler.border': lighten(bg.light, 0.04),
    'editorOverviewRuler.errorForeground': red.dark,
    'editorOverviewRuler.warningForeground': yellow.main,
    'editorOverviewRuler.infoForeground': elements.info,
    'editorOverviewRuler.bracketMatchForeground': bg.darker,
    'editorOverviewRuler.findMatchForeground': alpha(blue.light, 0.4),
    'editorOverviewRuler.rangeHighlightForeground': alpha(teal.main, 0.3),
    'editorOverviewRuler.selectionHighlightForeground': alpha(
      cyan.medium,
      0.25
    ),
    'editorOverviewRuler.wordHighlightForeground': alpha(purple.light, 0.35),
    'editorOverviewRuler.wordHighlightStrongForeground': alpha(
      purple.bright,
      0.45
    ),
    'editorOverviewRuler.modifiedForeground': git.modified,
    'editorOverviewRuler.addedForeground': git.added,
    'editorOverviewRuler.deletedForeground': git.deleted,
    'editorRuler.foreground': bg.darker,
    'editorError.foreground': red.dark,
    'editorWarning.foreground': yellow.main,
    'editorInfo.foreground': cyan.medium,
    'editorHint.foreground': cyan.medium,
    'editorGutter.modifiedBackground': git.modified,
    'editorGutter.addedBackground': git.added,
    'editorGutter.deletedBackground': git.deletedDark,
    'editorGhostText.foreground': special.ghostText,
    'minimapGutter.modifiedBackground': git.modifiedMinimap,
    'minimapGutter.addedBackground': git.addedMinimap,
    'minimapGutter.deletedBackground': git.deletedMinimap,
    'editorGroup.border': lighten(bg.light, 0.04),
    'editorGroup.dropBackground': bg.lighter,
    'editorGroupHeader.tabsBorder': bg.darker,
    'editorGroupHeader.tabsBackground': bg.main,
    'editorGroupHeader.noTabsBackground': bg.main,
    'editorGroupHeader.border': lighten(bg.light, 0.04),
    'editorPane.background': bg.editor,
    'editorWidget.foreground': fg.medium,
    'editorWidget.background': bg.light,
    'editorWidget.border': lighten(bg.light, 0.04),
    'editorWidget.resizeBorder': alpha(special.disabled, 0.4),
    'editorSuggestWidget.background': bg.light,
    'editorSuggestWidget.border': lighten(bg.light, 0.04),
    'editorSuggestWidget.selectedBackground': interactive.selected,
    'editorSuggestWidget.highlightForeground': blue.light,
    'editorCodeLens.foreground': ui.codeLens,
    'editorLightBulb.foreground': yellow.main,
    'editorLightBulbAutoFix.foreground': yellow.main,
    'editorInlayHint.foreground': special.ghostText,
    'peekView.border': lighten(bg.light, 0.04),
    'peekViewEditor.background': bg.light,
    'peekViewEditor.matchHighlightBackground': alpha(blue.light, 0.4),
    'peekViewTitle.background': bg.light,
    'peekViewTitleLabel.foreground': fg.brighter,
    'peekViewTitleDescription.foreground': fg.medium,
    'peekViewResult.background': bg.light,
    'peekViewResult.selectionForeground': fg.brighter,
    'peekViewResult.selectionBackground': alpha(blue.light, 0.4),
    'peekViewResult.lineForeground': fg.brighter,
    'peekViewResult.fileForeground': fg.medium,
    'peekViewResult.matchHighlightBackground': alpha(blue.light, 0.4),
  }
}
