import { palette } from '../../palette/index.js'
import { alpha, lighten, mix } from '../../utils/color.js'

export function generateEditorColors(): Record<string, string> {
  const { bg, fg, cyan, yellow, red, purple, teal, green, ui, neutral } =
    palette

  return {
    'selection.background': alpha(purple.dark, 0.2),
    'editor.background': bg.light,
    'editor.foreground': fg.light,
    'editor.foldBackground': alpha(bg.dark, 0.2),
    'editorLink.activeForeground': fg.light,
    'editor.selectionBackground': alpha(purple.dark, 0.2),
    'editor.inactiveSelectionBackground': alpha(purple.dark, 0.2),
    'editor.findMatchBackground': alpha(neutral.light, 0.2),
    'editor.findMatchBorder': yellow.main,
    'editor.findMatchHighlightBackground': alpha(neutral.light, 0.2),
    'editor.findRangeHighlightBackground': alpha(purple.dark, 0.2),
    'editor.rangeHighlightBackground': alpha(teal.main, 0.2),
    'editor.wordHighlightBackground': alpha(purple.light, 0.2),
    'editor.wordHighlightStrongBackground': alpha(purple.light, 0.2),
    'editor.selectionHighlightBackground': alpha(cyan.main, 0.2),
    'editorStickyScrollHover.background': alpha(purple.dark, 0.2),
    'editorCursor.foreground': fg.light,
    'editorIndentGuide.background1': lighten(bg.main, 0.05),
    'editorIndentGuide.activeBackground1': mix(neutral.dark, bg.main, 0.7),
    'editorLineNumber.foreground': neutral.dark,
    'editorLineNumber.activeForeground': fg.main,
    'editor.lineHighlightBackground': bg.light,
    'editorWhitespace.foreground': lighten(ui.badge, 0.08),
    'editorMarkerNavigation.background': bg.main,
    'editorHoverWidget.background': mix(bg.main, neutral.dark, 0.15),
    'editorHoverWidget.border': lighten(bg.main, 0.08),
    'editorBracketMatch.background': bg.main,
    'editorBracketMatch.border': lighten(bg.main, 0.02),
    'editorBracketHighlight.foreground1': neutral.light,
    'editorBracketHighlight.foreground2': cyan.light,
    'editorBracketHighlight.foreground3': purple.light,
    'editorBracketHighlight.foreground4': yellow.light,
    'editorBracketHighlight.foreground5': teal.light,
    'editorBracketHighlight.foreground6': green.main,
    'editorBracketHighlight.unexpectedBracket.foreground': red.dark,
    'editorBracketPairGuide.activeBackground1': neutral.light,
    'editorBracketPairGuide.activeBackground2': cyan.light,
    'editorBracketPairGuide.activeBackground3': purple.light,
    'editorBracketPairGuide.activeBackground4': yellow.light,
    'editorBracketPairGuide.activeBackground5': teal.light,
    'editorBracketPairGuide.activeBackground6': green.main,
    'editorOverviewRuler.border': lighten(bg.light, 0.02),
    'editorOverviewRuler.errorForeground': red.dark,
    'editorOverviewRuler.warningForeground': yellow.main,
    'editorOverviewRuler.infoForeground': mix(teal.main, green.main, 0.3),
    'editorOverviewRuler.bracketMatchForeground': bg.dark,
    'editorOverviewRuler.findMatchForeground': alpha(neutral.light, 0.4),
    'editorOverviewRuler.rangeHighlightForeground': alpha(teal.main, 0.3),
    'editorOverviewRuler.selectionHighlightForeground': alpha(cyan.main, 0.25),
    'editorOverviewRuler.wordHighlightForeground': alpha(purple.light, 0.35),
    'editorOverviewRuler.wordHighlightStrongForeground': alpha(
      purple.light,
      0.45
    ),
    'editorOverviewRuler.modifiedForeground': mix(neutral.main, bg.main, 0.65),
    'editorOverviewRuler.addedForeground': mix(teal.main, bg.main, 0.8),
    'editorOverviewRuler.deletedForeground': mix(red.main, bg.main, 0.7),
    'editorRuler.foreground': bg.dark,
    'editorError.foreground': red.dark,
    'editorWarning.foreground': yellow.main,
    'editorInfo.foreground': cyan.main,
    'editorHint.foreground': cyan.main,
    'editorGutter.modifiedBackground': mix(neutral.main, bg.main, 0.65),
    'editorGutter.addedBackground': mix(teal.main, bg.main, 0.8),
    'editorGutter.deletedBackground': mix(red.main, bg.main, 0.65),
    'editorGhostText.foreground': neutral.dark,
    'minimapGutter.modifiedBackground': mix(neutral.main, bg.main, 0.6),
    'minimapGutter.addedBackground': mix(teal.main, bg.main, 0.75),
    'minimapGutter.deletedBackground': mix(red.main, bg.main, 0.6),
    'editorGroup.border': lighten(bg.light, 0.02),
    'editorGroup.dropBackground': lighten(bg.light, 0.02),
    'editorGroupHeader.tabsBorder': bg.dark,
    'editorGroupHeader.tabsBackground': bg.main,
    'editorGroupHeader.noTabsBackground': bg.main,
    'editorGroupHeader.border': lighten(bg.main, 0.02),
    'editorPane.background': bg.light,
    'editorWidget.foreground': fg.light,
    'editorWidget.background': mix(bg.main, neutral.dark, 0.15),
    'editorWidget.border': lighten(bg.main, 0.08),
    'editorWidget.resizeBorder': lighten(bg.main, 0.08),
    'widget.shadow': alpha(ui.black, 0.3),
    'editorSuggestWidget.background': bg.main,
    'editorSuggestWidget.border': lighten(bg.main, 0.08),
    'editorSuggestWidget.selectedBackground': mix(bg.main, purple.dark, 0.12),
    'editorSuggestWidget.highlightForeground': neutral.light,
    'editorCodeLens.foreground': fg.dark,
    'editorLightBulb.foreground': yellow.main,
    'editorLightBulbAutoFix.foreground': yellow.main,
    'editorInlayHint.foreground': neutral.main,
    'peekView.border': lighten(bg.main, 0.08),
    'peekViewEditor.background': bg.main,
    'peekViewEditor.matchHighlightBackground': alpha(neutral.light, 0.4),
    'peekViewTitle.background': bg.dark,
    'peekViewTitleLabel.foreground': fg.light,
    'peekViewTitleDescription.foreground': fg.main,
    'peekViewResult.background': bg.main,
    'peekViewResult.selectionForeground': fg.light,
    'peekViewResult.selectionBackground': alpha(neutral.light, 0.4),
    'peekViewResult.lineForeground': fg.light,
    'peekViewResult.fileForeground': fg.main,
    'peekViewResult.matchHighlightBackground': alpha(neutral.light, 0.4),
  }
}
