import { c, colorRules } from '../../utils/color-builder.js'

export function generateGitColors(): Record<string, string> {
  return colorRules()
    .addGroup('gitDecoration', {
      addedResourceForeground: c.green.main,
      modifiedResourceForeground: c.yellow.main,
      deletedResourceForeground: c.red.main,
      renamedResourceForeground: c.blue.light,
      stageDeletedResourceForeground: c.red.light,
      stageModifiedResourceForeground: c.yellow.light,
      untrackedResourceForeground: c.blue.main,
      ignoredResourceForeground: c.fg.dark,
      conflictingResourceForeground: c.orange.main,
      conflictResourceForeground: c.orange.main,
      submoduleResourceForeground: c.purple.main,
      stageUriTooltipForeground: c.fg.main,
      stagedAddedResourceForeground: c.green.light,
      stagedDeletedResourceForeground: c.red.light,
      stagedModifiedResourceForeground: c.yellow.light,
      unmergedResourceForeground: c.orange.main,
      incomingAddedResourceForeground: c.green.dark,
      incomingDeletedResourceForeground: c.red.dark,
      incomingModifiedResourceForeground: c.yellow.dark,
      incomingRenamedResourceForeground: c.blue.dark,
      workspaceModifiedResourceForeground: c.yellow.main,
      distantAddedResourceForeground: c.green.main,
      distantDeletedResourceForeground: c.red.main,
      distantModifiedResourceForeground: c.yellow.main,
      distantRenamedResourceForeground: c.blue.main,
      distantResourceForeground: c.fg.main,
      trackedResourceForeground: c.fg.main,
      optimisticModifiedResourceForeground: c.yellow.main,
      pathModifiedResourceForeground: c.orange.main,
    })
    .addGroup('scm', {
      foreground: c.fg.main,
      labelForeground: c.fg.main,
      border: c.neutral.main,
      providerBorder: c.neutral.main,
      actionButtonBorder: c.blue.main,
      titleForeground: c.fg.bright,
      titleBorder: c.neutral.main,
      titleBackground: c.bg.dark,
      groupForeground: c.blue.light,
      groupBorder: c.neutral.dark,
      groupLabelForeground: c.blue.light,
      groupTitleBackground: c.bg.main,
      itemForeground: c.fg.main,
      itemIconForeground: c.blue.main,
      itemInlineActionForeground: c.fg.main,
      itemInlineActionBackground: c.bg.main,
      itemInlineActionHoverBackground: c.bg.light,
      historyItemBorder: c.neutral.main,
      historyItemForeground: c.fg.main,
      historyItemLabelForeground: c.fg.main,
      historyItemBadgeBackground: c.rose.main,
      historyItemBadgeForeground: c.ui.black,
    })
    .addGroup('git', {
      statusCurrentBranch: c.blue.light,
      statusRemoteBranch: c.purple.main,
      statusHeadBackground: c.bg.dark,
      statusHeadForeground: c.blue.light,
      statusAdded: c.green.main,
      statusCopied: c.cyan.main,
      statusDeleted: c.red.main,
      statusIgnored: c.fg.dark,
      statusModified: c.yellow.main,
      statusRenamed: c.blue.light,
      statusUnmerged: c.orange.main,
      statusUntracked: c.blue.main,
      separatorActiveBackground: c.neutral.main,
      separatorInactiveBackground: c.neutral.dark,
      lineUncommittedForeground: c.blue.main,
      lineAddedForeground: c.green.main,
      lineDeletedForeground: c.red.main,
      lineSelectedForeground: c.blue.light,
      lineSelectedBackground: `${c.bg.dark}80`,
      lineChangedForeground: c.yellow.main,
      lineBlameForeground: c.fg.main,
      lineNewModified: c.yellow.main,
      lineNewAdded: c.green.main,
      lineNewDeleted: c.red.main,
      stagedChangesHover: c.bg.main,
    })
    .build()
}
