import { palette } from '../../palette'
import { alpha, lighten, mix } from '../../utils/color'

export function generateMiscColors(): Record<string, string> {
  const {
    bg,
    fg,
    blue,
    yellow,
    red,
    cyan,
    green,
    purple,
    orange,
    teal,
    special,
  } = palette

  return {
    'walkThrough.embeddedEditorBackground': bg.main,
    'textLink.foreground': cyan.light,
    'textLink.activeForeground': lighten(cyan.light, 0.2),
    'textPreformat.foreground': palette.ui.preformat,
    'textBlockQuote.background': bg.main,
    'textCodeBlock.background': bg.main,
    'textSeparator.foreground': special.indentActive,
    'debugExceptionWidget.border': palette.ui.debugException,
    'debugExceptionWidget.background': bg.darker,
    'debugToolBar.background': bg.darker,
    'debugConsole.infoForeground': fg.medium,
    'debugConsole.errorForeground': palette.ui.debugError,
    'debugConsole.sourceForeground': fg.medium,
    'debugConsole.warningForeground': yellow.muted,
    'debugConsoleInputIcon.foreground': teal.main,
    'editor.stackFrameHighlightBackground': alpha(
      palette.ui.stackFrameHighlight,
      0.125
    ),
    'editor.focusedStackFrameHighlightBackground': alpha(teal.main, 0.125),
    'debugView.stateLabelForeground': fg.medium,
    'debugView.stateLabelBackground': mix(bg.darkest, blue.primary, 0.1),
    'debugView.valueChangedHighlight': alpha(blue.primary, 0.67),
    'debugTokenExpression.name': cyan.light,
    'debugTokenExpression.value': fg.bright,
    'debugTokenExpression.string': green.main,
    'debugTokenExpression.boolean': orange.main,
    'debugTokenExpression.number': orange.main,
    'debugTokenExpression.error': palette.ui.debugError,
    'debugIcon.breakpointForeground': red.dark,
    'debugIcon.breakpointDisabledForeground':
      palette.ui.debugBreakpointDisabled,
    'debugIcon.breakpointUnverifiedForeground':
      palette.ui.debugBreakpointUnverified,
    'notebook.editorBackground': bg.editor,
    'notebook.cellEditorBackground': bg.main,
    'notebook.cellBorderColor': bg.darker,
    'notebook.focusedCellBorder': lighten(bg.main, 0.02),
    'notebook.cellStatusBarItemHoverBackground': bg.lighter,
    'charts.red': red.main,
    'charts.blue': blue.medium,
    'charts.yellow': yellow.main,
    'charts.orange': orange.main,
    'charts.green': green.dark,
    'charts.purple': purple.dark,
    'charts.foreground': fg.bright,
    'charts.lines': bg.main,
    'scmGraph.historyItemHoverLabelForeground': bg.darkest,
    'scmGraph.foreground1': orange.main,
    'scmGraph.foreground2': yellow.main,
    'scmGraph.foreground3': green.dark,
    'scmGraph.foreground4': blue.medium,
    'scmGraph.foreground5': purple.light,
    'scmGraph.historyItemHoverAdditionsForeground': green.dark,
    'scmGraph.historyItemHoverDeletionsForeground': red.main,
    'scmGraph.historyItemRefColor': palette.ui.scmGraphRef,
    'scmGraph.historyItemRemoteRefColor': green.dark,
    'scmGraph.historyItemBaseRefColor': purple.dark,
    'scmGraph.historyItemHoverDefaultLabelForeground': fg.brighter,
    'merge.currentHeaderBackground': alpha(green.dark, 0.15),
    'merge.currentContentBackground': alpha(teal.dark, 0.27),
    'merge.incomingHeaderBackground': alpha(blue.primary, 0.67),
    'merge.incomingContentBackground': alpha(blue.primary, 0.27),
    'mergeEditor.change.background': alpha(green.dark, 0.15),
    'mergeEditor.change.word.background': alpha(green.dark, 0.25),
    'mergeEditor.conflict.unhandledUnfocused.border': alpha(yellow.main, 0.53),
    'mergeEditor.conflict.unhandledFocused.border': alpha(yellow.main, 0.69),
    'mergeEditor.conflict.handledUnfocused.border': alpha(green.dark, 0.15),
    'mergeEditor.conflict.handledFocused.border': alpha(green.dark, 0.4),
    'mergeEditor.conflict.handled.minimapOverViewRuler': teal.dark,
    'mergeEditor.conflict.unhandled.minimapOverViewRuler': yellow.main,
    'gitlens.trailingLineForegroundColor': special.ghostText,
    'gitlens.gutterUncommittedForegroundColor': blue.medium,
    'gitlens.gutterForegroundColor': fg.medium,
    'gitlens.gutterBackgroundColor': bg.main,
    'notificationCenterHeader.background': mix(bg.darkest, blue.primary, 0.1),
    'notifications.background': mix(bg.darkest, blue.primary, 0.1),
    'notificationLink.foreground': blue.light,
    'notificationsErrorIcon.foreground': palette.ui.notificationError,
    'notificationsWarningIcon.foreground': palette.ui.notificationWarning,
    'notificationsInfoIcon.foreground': cyan.medium,
    'menubar.selectionForeground': fg.brighter,
    'menubar.selectionBackground': alpha(blue.primary, 0.2),
    'menubar.selectionBorder': lighten(
      mix(bg.darkest, blue.primary, 0.1),
      0.04
    ),
    'menu.foreground': fg.medium,
    'menu.background': mix(bg.darkest, blue.primary, 0.1),
    'menu.selectionForeground': lighten(fg.brightest, 0.4),
    'menu.selectionBackground': alpha(blue.primary, 0.4),
    'menu.separatorBackground': lighten(
      mix(bg.darkest, blue.primary, 0.1),
      0.06
    ),
    'menu.border': lighten(mix(bg.darkest, blue.primary, 0.1), 0.02),
    'chat.requestBorder': bg.lighter,
    'chat.avatarBackground': blue.primary,
    'chat.avatarForeground': fg.brighter,
    'chat.slashCommandBackground': bg.dark,
    'chat.slashCommandForeground': blue.medium,
    'inlineChat.foreground': fg.brighter,
    'inlineChatInput.background': bg.lighter,
    'inlineChatDiff.inserted': alpha(green.dark, 0.25),
    'inlineChatDiff.removed': alpha(red.dark, 0.26),
  }
}
