import { palette } from '../../palette'
import { alpha } from '../../utils/color'

export function generateMiscColors(): Record<string, string> {
  const { bg, fg, blue, yellow, red, cyan, green, purple, orange, teal } =
    palette

  return {
    'walkThrough.embeddedEditorBackground': bg.main,
    'textLink.foreground': blue.light,
    'textLink.activeForeground': cyan.light,
    'textPreformat.foreground': '#9699a8',
    'textBlockQuote.background': bg.main,
    'textCodeBlock.background': bg.main,
    'textSeparator.foreground': palette.special.indentActive,
    'debugExceptionWidget.border': '#963c47',
    'debugExceptionWidget.background': bg.darker,
    'debugToolBar.background': bg.darker,
    'debugConsole.infoForeground': fg.medium,
    'debugConsole.errorForeground': '#bb616b',
    'debugConsole.sourceForeground': fg.medium,
    'debugConsole.warningForeground': yellow.muted,
    'debugConsoleInputIcon.foreground': teal.main,
    'editor.stackFrameHighlightBackground': alpha('#e2bd3a', 0.125),
    'editor.focusedStackFrameHighlightBackground': alpha(teal.main, 0.125),
    'debugView.stateLabelForeground': fg.medium,
    'debugView.stateLabelBackground': bg.dark,
    'debugView.valueChangedHighlight': alpha(blue.primary, 0.67),
    'debugTokenExpression.name': cyan.light,
    'debugTokenExpression.value': fg.bright,
    'debugTokenExpression.string': green.main,
    'debugTokenExpression.boolean': orange,
    'debugTokenExpression.number': orange,
    'debugTokenExpression.error': '#bb616b',
    'debugIcon.breakpointForeground': red.dark,
    'debugIcon.breakpointDisabledForeground': '#414761',
    'debugIcon.breakpointUnverifiedForeground': '#c24242',
    'notebook.editorBackground': bg.editor,
    'notebook.cellEditorBackground': bg.main,
    'notebook.cellBorderColor': bg.darker,
    'notebook.focusedCellBorder': palette.special.border,
    'notebook.cellStatusBarItemHoverBackground': bg.light,
    'charts.red': red.main,
    'charts.blue': blue.medium,
    'charts.yellow': yellow.main,
    'charts.orange': orange,
    'charts.green': green.dark,
    'charts.purple': purple.dark,
    'charts.foreground': fg.bright,
    'charts.lines': bg.main,
    'scmGraph.historyItemHoverLabelForeground': '#1b1e2e',
    'scmGraph.foreground1': orange,
    'scmGraph.foreground2': yellow.main,
    'scmGraph.foreground3': green.dark,
    'scmGraph.foreground4': blue.medium,
    'scmGraph.foreground5': purple.light,
    'scmGraph.historyItemHoverAdditionsForeground': green.dark,
    'scmGraph.historyItemHoverDeletionsForeground': red.main,
    'scmGraph.historyItemRefColor': '#506fca',
    'scmGraph.historyItemRemoteRefColor': green.dark,
    'scmGraph.historyItemBaseRefColor': purple.dark,
    'scmGraph.historyItemHoverDefaultLabelForeground': fg.brighter,
    'merge.currentHeaderBackground': alpha(green.dark, 0.15),
    'merge.currentContentBackground': alpha('#007a75', 0.27),
    'merge.incomingHeaderBackground': alpha(blue.primary, 0.67),
    'merge.incomingContentBackground': alpha(blue.primary, 0.27),
    'mergeEditor.change.background': alpha(green.dark, 0.15),
    'mergeEditor.change.word.background': alpha(green.dark, 0.25),
    'mergeEditor.conflict.unhandledUnfocused.border': alpha(yellow.main, 0.53),
    'mergeEditor.conflict.unhandledFocused.border': alpha(yellow.main, 0.69),
    'mergeEditor.conflict.handledUnfocused.border': alpha(green.dark, 0.15),
    'mergeEditor.conflict.handledFocused.border': alpha(green.dark, 0.4),
    'mergeEditor.conflict.handled.minimapOverViewRuler': teal.dark,
    'mergeEditor.conflict.unhandled.minimapOverViewRuler': yellow.main,
    'gitlens.trailingLineForegroundColor': palette.special.ghostText,
    'gitlens.gutterUncommittedForegroundColor': blue.medium,
    'gitlens.gutterForegroundColor': fg.medium,
    'gitlens.gutterBackgroundColor': bg.main,
    'notificationCenterHeader.background': bg.darker,
    'notifications.background': bg.darker,
    'notificationLink.foreground': blue.light,
    'notificationsErrorIcon.foreground': '#bb616b',
    'notificationsWarningIcon.foreground': '#bba461',
    'notificationsInfoIcon.foreground': cyan.medium,
    'menubar.selectionForeground': fg.brighter,
    'menubar.selectionBackground': bg.lighter,
    'menubar.selectionBorder': '#1b1e2e',
    'menu.foreground': fg.medium,
    'menu.background': bg.main,
    'menu.selectionForeground': fg.brighter,
    'menu.selectionBackground': bg.lighter,
    'menu.separatorBackground': bg.darker,
    'menu.border': bg.darker,
    'chat.requestBorder': bg.darker,
    'chat.avatarBackground': blue.primary,
    'chat.avatarForeground': fg.brighter,
    'chat.slashCommandBackground': bg.dark,
    'chat.slashCommandForeground': blue.medium,
    'inlineChat.foreground': fg.brighter,
    'inlineChatInput.background': bg.dark,
    'inlineChatDiff.inserted': alpha(green.dark, 0.25),
    'inlineChatDiff.removed': alpha(red.dark, 0.26),
  }
}
